### ISSUE TITLE
Can't scroll when Circle list inside Scrollview

### ISSUE THREAD

**Issue by Mohanedy98** [asjqkkkk/circle_list#1]
SingleChildScrollView -> Column -> Circle List 
The Circle List doesn't respond to gestures

**Comment by asjqkkkk** [comment]
> SingleChildScrollView -> Column -> Circle List
> The Circle List doesn't respond to gestures

It looks like a problem with sliding conflicts.
Sorry,now I am busy with work, I will take the time to see how to solve this problem.

**Comment by MeliGualaX** [comment]
Hello, this guy had the same problem and it solved using a CustomPanGestureRecognizer to win in the arena when two gestures interact. I really tried to implement in your code but i failed,  maybe this post can help you. 
https://medium.com/flutter-community/combining-multiple-gesturedetectors-in-flutter-26d899d008b2

Greetings!
