### ISSUE TITLE
If i needn't rotate,How should I do?

### ISSUE THREAD

**Issue by cn-Meepo** [asjqkkkk/circle_list#5]
excuse me,If i needn't rotate,How should I do?

**Comment by asjqkkkk** [comment]
try to use `AbsorbPointer ` wrap it😄

**Comment by cn-Meepo** [comment]
@asjqkkkk I need tap every ClipRRectand need't rotate

**Comment by cn-Meepo** [comment]
@asjqkkkk  maybe, shoud add one isRotate to choose rotate or not. all right?

**Comment by asjqkkkk** [comment]
> @asjqkkkk maybe, shoud add one isRotate to choose rotate or not. all right?

😂I didn't think about it， but it's not hard to do.
It's a good idea.
Because I didn't put the original dart package file here, it's not convenient to submit the pull request for the moment. Let me upgrade to v1.0.3 tomorrow to solve this problem

**Comment by cn-Meepo** [comment]
@asjqkkkk thanks

**Comment by asjqkkkk** [comment]
> @asjqkkkk thanks

hi, now you can update to v1.0.3

and use rotateMode to stop rotate😄
```
CircleList( rotateMode: RotateMode.stopRotate )
```

**Comment by cn-Meepo** [comment]
@asjqkkkk 回头才发现我俩是逗比啊，O(∩_∩)O哈哈~

**Comment by asjqkkkk** [comment]
> @asjqkkkk 回头才发现我俩是逗比啊，O(∩_∩)O哈哈~

嗨，亏我辛苦用google translate😂

**Comment by cn-Meepo** [comment]
> > @asjqkkkk 回头才发现我俩是逗比啊，O(∩_∩)O哈哈~
> 
> 嗨，亏我辛苦用google translate😂

我刚看到不久😂😂😂
