### ISSUE TITLE
add end angle

### ISSUE THREAD

**Issue by MeliGualaX** [asjqkkkk/circle_list#6]
Is it posible to add a property that allows to move only in a certain range of angles?. What i want is that the child widgets only move from 0º to 180º  (half circle) and no more. Is possible to do that? 
Thanks your work help me a lot!

**Comment by asjqkkkk** [comment]
It's not hard, Later I will think about how to implement this function specifically

**Comment by asjqkkkk** [comment]
Hi, you can update to v1.0.4 and use `DragAngleRange` to solve this problem

**Comment by MeliGualaX** [comment]
hi, thanks for the quick reply! I already test it. Could be that is not working for negative coords?
dragAngleRange: DragAngleRange(0,1) => this works!
dragAngleRange: DragAngleRange(0,-1) => this not

**Comment by asjqkkkk** [comment]
start should be less than end
have a try for (-pi, 0.0)

**Comment by MeliGualaX** [comment]
Thanks! That work! I will close the issue.
