### ISSUE TITLE
Add Nullsafety support

### ISSUE THREAD

**Issue by prateekmedia** [asjqkkkk/circle_list#7]
https://dart.dev/null-safety/migration-guide

**Comment by asjqkkkk** [comment]
no problem

**Comment by prateekmedia** [comment]
@asjqkkkk Please also update `flare_flutter` to `3.0.0` before publishing to pub.dev in example project.

Also do below things:
- [ ] Update version in pubspec.yaml
- [ ] Add CHANGELOG for new version
- [ ] Update README, for new version

**Comment by lakshyapunhani** [comment]
Is it updated for null safety? @asjqkkkk

**Comment by prateekmedia** [comment]
> Is it updated for null safety? @asjqkkkk

```dart
on github  - true
on pub.dev - false
```

**Comment by Scienticious** [comment]
Hello @prateekmedia,   Please  convert this package on null safe in the pub.dev

**Comment by prateekmedia** [comment]
@Scienticious I don't have access to pub.dev of circle_list, Please contact @asjqkkkk for that, he may be busy so till then you can use github repo in your pubspec.yaml.

**Comment by asjqkkkk** [comment]
v1.0.5 is ok for this issue
